
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pg_container
    environment:
      POSTGRES_USER: gokila
      POSTGRES_PASSWORD: goki
      POSTGRES_DB: fastapi_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gokila -d fastapi_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://gokila:goki@db:5432/fastapi_db
    volumes:
      - .:/app  # Optional: if you want live reload (only for development)
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata:
